name: example_common
description: Common components and utils for example apps.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.7.0

dev_dependencies:
  amplify_lints: ">=2.0.2 <2.1.0"
  # TODO(equartey): Can be bumped when test_api is bumped to ^0.7.2 in integration_test
  test: ">=1.25.0 <=1.26.0"
